### PR TITLE
edit readme

### PR DESCRIPTION
**Pull request by theandychung**
added more detailed tutorial

### CODE REVIEW

**Comment by nondanee** [comment]
i am sorry for rejection
but thank you for your kind attention
i had added thorough tutorial in issue

**Comment by theandychung** [comment]
np

**Comment by xiumuyu** [comment]
MacOS 下终端开启后能显示MITM > music.163.com，但是实际上没有用

**Comment by nondanee** [comment]
没用怎么体现？
为什么要在 PR 里回复？

**Pull request closed without merging**
